image: ubuntu:18.04
stages:
  - test
 
test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - cd src
  - python3 -m pytest saveTest.py
